auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3

  aws:
    s3: s3://access_key:secret_key@172.28.0.10:9000/log
    endpoint: 172.28.0.10:9000
    insecure: true
    s3forcepathstyle: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 4320h

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 5m
