version: "3"

networks:
  local_containers:
    external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/root/.ollama
    ports:
      - 127.0.0.1:1030:11434
    # https://github.com/containers/podman-compose/pull/867
    networks:
      local_containers:
        ipv4_address: 10.25.10.30
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
