version: "3.8"

services:
  open-webui:
    image: open-webui/open-webui:main
    container_name: open-webui
    restart: always
    volumes:
      - ./data/webui:/app/backend/data
    ports:
      - 127.0.0.1:1170:8080
    env_file:
      - .env
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 127.0.0.1:1171:11434
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
