version: "3"

networks:
  local_containers:
    external: true

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - 127.0.0.1:1150:80
    networks:
      local_containers:
        ipv4_address: 10.25.11.50
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
