version: "3"

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:1160:80
    volumes:
      - ./data:/app/data
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
