version: "3"

services:
  snapdrop:
    image: sigoden/dufs
    container_name: dufs
    command: /data -A -a ${ADMIN}@/:rw -a ${USER1}@/public:rw -a @/public/pub
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:1190:5000
    volumes:
      - ./data:/data:Z
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
