version: "3.9"

networks:
  local_containers:
    external: true

services:
  anki-sync:
    image: localhost/anki-sync:25.09.2
    container_name: anki-sync
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./anki_data:/anki_data:Z
    ports:
      - 0.0.0.0:1150:8080
    networks:
      local_containers:
        ipv4_address: 10.25.11.50
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
