set encoding=utf-8
set number
set relativenumber

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
"set autowriteall

if has("autocmd")
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
endif

set autoindent
"set cindent
"set smartindent

set ruler
set showcmd

"set cursorline
"hi CursorLine term=bold cterm=bold guibg=Grey40

set incsearch
set hlsearch

if has("syntax")
  syntax on
endif

"set pastetoggle=F3

" plugins
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"call plug#begin('~/.vim/plugged')
"call plug#end()

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

nnoremap q: <nop>
nnoremap Q <nop>
