{
 "title": "Host Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "host", "label": "Host", "query": "label_values(host)" },
   { "name": "interface", "label": "Interface", "query": "if1,if2" },
   { "name": "disk", "label": "Disk", "query": "disk1,disk2" }
  ]
 },
 "panels": [
  {
   "title": "Current CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap cpu_usage\n  | __error__=\"\" \n  [10s]) by (${host})",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Load 🕐",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap cpu_load_1 \n  | __error__=\"\" \n  [10s]) by (${host})",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Load 🕔",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap cpu_load_5 \n  | __error__=\"\" \n  [10s]) by (${host})",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Load 🕒",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap cpu_load_15 \n  | __error__=\"\" \n  [10s]) by (${host})",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Current Application Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap app_mem \n  | __error__=\"\" \n  [10s]) by (${host})) / on()\n(last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap total_mem \n  | __error__=\"\" \n  [10s]) by (${host}))",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Current Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap used_mem \n  | __error__=\"\" \n  [10s]) by (${host})) / on()\n(last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap total_mem \n  | __error__=\"\" \n  [10s]) by (${host}))  ",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap total_mem \n  | __error__=\"\" \n  [10s]) by (${host})\n  ",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap total_swap\n  | __error__=\"\" \n  [10s]) by (${host})",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Used Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap used_swap \n  | __error__=\"\" \n  [10s]) by (${host})) / on()\n(last_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap total_swap\n  | __error__=\"\" \n  [10s]) by (${host}))",
     "maxLines": 1,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Network in - ${interface} / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap network_${interface}_in\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "${interface}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Network Packets in - ${interface} / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap network_${interface}_pkg_in\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "${interface}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Network out - ${interface} / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap network_${interface}_out\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "${interface}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Network Packets out - ${interface} / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap network_${interface}_out\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "${interface}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Disk in / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap disk_disk_in\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "disk",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Disk out / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap disk_disk_out\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "disk",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Disk Wirte / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap disk_${disk}_write\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "${disk}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Disk Read / 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "max_over_time(\n  {host=\"$host\", job=\"host_log\"} \n  | json \n  | unwrap disk_${disk}_read\n  | __error__=\"\" \n  [10s]) by (${host})",
     "legendFormat": "${disk}",
     "resolution": 1
    }
   ]
  }
 ]
}