version: '3.0'

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: https://vault.example.com
      SIGNUPS_ALLOWED: true
      WEB_VAULT_ENABLED: true
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: SECRET_TOKEN
      DATABASE_URL: /data/vaultwarden.db
      LOG_FILE: /data/vaultwarden.log
    volumes:
      - ./data:/data:Z
    #env_file:
    #  - config.env
    ports:
      - 8080:80
      - 3012:3012
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
