server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.2.3.20:3100/loki/api/v1/push

scrape_configs:
 - job_name: hwecs-host
   pipeline_stages:
   - json:
       expressions:
         time: timestamp
   - timestamp:
       source: time
       format: RFC3339Nano
   static_configs:
   - targets:
      - localhost
     labels:
      host: hwecs
      job: host_log
      __path__: /logs/host/json_host.log
 - job_name: hwecs-nginx
   pipeline_stages:
   - json:
       expressions:
         time: msec
   - timestamp:
       source: time
       format: Unix
       location: Asia/Shanghai
   static_configs:
   - targets:
      - localhost
     labels:
      host: hwecs
      job: nginx_access_log
      __path__: /logs/nginx/json_access.log
