version: '3.0'

networks:
  podman-br-con:
    external: true

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./config:/etc/promtail/config:Z
      - /data/logs/nginx:/logs/nginx:Z
      - /data/logs/host:/logs/host:Z
    command: -config.file=/etc/promtail/config/promtail-config.yaml
    networks:
      - podman-br-con
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
