version: '3'

# https://github.com/whyour/qinglong
services:
  web:
    # alpine 基础镜像版本
    image: whyour/qinglong:latest
    # debian-slim 基础镜像版本
    # image: whyour/qinglong:debian  
    container_name: qinglong
    volumes:
      - ./data:/ql/data:Z
    ports:
      - "127.0.0.1:1150:5700"
    environment:
      # 部署路径非必须，以斜杠开头和结尾，比如 /test/
      QlBaseUrl: '/'
    restart: always
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
