version: "3"

services:
  web:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:1150:5700"
    volumes:
      - ./data:/ql/data
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
