version: "3"

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:1180:8080
    volumes:
      - ./data:/home/coder
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
