version: '3.0'

networks:
  docker-br-con:
    external: true

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./config:/etc/promtail/config
      - /data/logs/nginx:/logs/nginx
      - /data/logs/host:/logs/host
    command: -config.file=/etc/promtail/config/promtail.yaml
    networks:
      docker-br-con:
        ipv4_address: 10.2.3.10
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "10"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    #ports:
    #  - 8081:3100
    volumes:
      - ./config:/etc/loki/config
    #command: -config.file=/etc/loki/config/loki-config.yaml
    command: -config.file=/etc/loki/config/loki.yaml
    networks:
      docker-br-con:
        ipv4_address: 10.2.3.20
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "10"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    #env_file:
    #  - ./config/grafana.env
    volumes:
      - ./config/custom.ini:/tmp/custom.ini
      - ./grafana:/var/lib/grafana
    command: --config /tmp/custom.ini
    #ports:
    #  - 8082:3000
    networks:
      docker-br-con:
        ipv4_address: 10.2.3.30
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "10"
