version: "3"

services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    restart: always
    environment:
      LOG_FILE: /data/memos.log
    env_file:
      - .env
    ports:
      - 127.0.0.1:1130:5230
    volumes:
      - ./data:/var/opt/memos
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
