version: "3"

networks:
  local_containers:
    external: true

services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 127.0.0.1:1160:5230
    networks:
      local_containers:
        ipv4_address: 10.25.11.60
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
