version: "3"

services:
  snapdrop:
    image: linuxserver/pairdrop:latest
    container_name: pairdrop
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/config:Z
    ports:
      - 127.0.0.1:1140:80
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
