version: "3.9"

networks:
  local_containers:
    external: true

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./coder:/home/coder:Z
    ports:
      - 0.0.0.0:1130:8080
    networks:
      local_containers:
        ipv4_address: 10.25.11.30
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
