version: "3"

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - 127.0.0.1:1120:80
      - 127.0.0.1:1121:3012
    networks:
      - podman-br-con
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
