version: "3.9"

networks:
  local_containers:
    external: true

services:
  matrix-synapse:
    image: ghcr.io/element-hq/synapse:latest
    container_name: matrix-synapse
    restart: unless-stopped
    # command: generate
    env_file:
      - .env
    volumes:
      - ./data:/data:Z
    ports:
      - 0.0.0.0:1170:8008
    networks:
      local_containers:
        ipv4_address: 10.25.11.70
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
