version: "3.9"

networks:
  local_containers:
    external: true

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/cache/ntfy/attachments:Z
    ports:
      - 0.0.0.0:1180:80
    networks:
      local_containers:
        ipv4_address: 10.25.11.80
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
