version: '3.8'

services:
  snapdrop:
    image: linuxserver/snapdrop:latest
    container_name: snapdrop
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
      LOG_FILE: /config/snapdrop.log
    volumes:
      - ./data:/config:Z
    ports:
      - 127.0.0.1:1140:80
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
