# aliases
alias g='git'
alias ga='git add'
alias gc='git commit'
alias gc='git commit --amend'
alias gcs='git commit -S'
alias gcsa='git commit -S --amend'
alias gp='git push'
alias gl='git pull'
alias gpm='git push origin main'
alias glm='git pull origin main'
alias gst='git status'
alias glog='git log'
alias glogc='git logc'
alias gck='git checkout'
alias gb='git branch'
alias gt='git tag'
