version: "3.0"

networks:
  docker-br-log:
    external: true

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    #ports:
    #  - 127.0.0.1:9000:9000
    #  - 127.0.0.1:9001:9001
    volumes:
      - ./config:/root/.minio
      - ./data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    networks:
      docker-br-log:
        ipv4_address: 172.28.0.10
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "10"
