version: "3"

networks:
  podman-br-con:
    external: true

services:
  mysql:
    image: library/mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 0.0.0.0:1110:3306
    networks:
      - podman-br-con
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "3"
