version: '3.8'

networks:
  podman-br-con:
    external: true

services:
  mysql:
    image: library/mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_passwd
    volumes:
      - ./data:/var/lib/mysql:Z
    networks:
      - podman-br-con
    ports:
      - 0.0.0.0:1110:3306
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
