version: '3.8'

networks:
  podman-br-con:
    external: true

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: https://vault.example.com
      SIGNUPS_ALLOWED: true
      WEB_VAULT_ENABLED: true
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: SECRET_TOKEN
      DATABASE_URL: /data/vaultwarden.db
      LOG_FILE: /data/vaultwarden.log
    volumes:
      - ./data:/data:Z
    #env_file:
    #  - config.env
    networks:
      - podman-br-con
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:3012:3012
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
        max-file: "10"
